name: HTML checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  htmlhint:
    name: HTMLHint (lint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Pas besoin de package.json : on utilise npx directement
      - name: Run HTMLHint
        run: npx --yes htmlhint "**/*.html" || (echo "HTMLHint found issues"; exit 1)

  w3c:
    name: W3C HTML Validator (vnu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Utilise l'image officielle validator.nu (vnu-jar) en Docker
      - name: Validate HTML with vnu
        run: |
          docker run --rm -v "${{ github.workspace }}:/site" ghcr.io/validator/validator:latest \
            --skip-non-html --errors-only --asciiquotes --also-check-css /site